name: "actions"
description: "Toolbox for Github Actions"
inputs:
    githubToken:
        description: "${{ secrets.GITHUB_TOKEN }}"
        required: true
    slackToken:
        description: "Slack Bot Token with chat:write, channels:history, groups:history, im:history and mpim:history"
        required: true
    slackChannel:
        description: "Slack Channel ID"
        required: true
    slackAccounts:
        description: "GitHub - Slack Account Pairing JSON File Path, { github: slack, github: slack } style"
        default: "./github/accounts.json"
runs:
    using: "node16"
    main: "dist/index.js"
