name: "actions"
description: "Toolbox for Github Actions"
inputs:
    githubToken:
        description: "GitHub API access token"
        required: true
    slackToken:
        description: "Slack Bot Token with chat:write, channels:history, groups:history, im:history and mpim:history"
        required: true
    slackChannel:
        description: "Slack Channel ID"
        required: true
    slackAccounts:
        description: "GitHub - Slack Account Pairing JSON string, { githubA: slackA, githubB: slackB ... } style"
        default: "{}"
    emptyBodyWarning:
        description: "Display template content to project contributors when the body of the pull request is empty."
        default: "Caution, body of this pull request is empty."
    pushMessage:
        description: "You can send a message in a workflow with a merge commit fired by a pull request merge operation."
        default: "Deployment flow complete"
runs:
    using: "node16"
    main: "dist/index.js"
