name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: node_modules
        run: npm ci
      - name: test
        run: npm run test
      - name: build
        run: npm run build && git add build && npm run release
